amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}
  vhost: ${AMQP_RABBIT_USERNAME}

keycloak:
  enabled: true
  realm: ${KEYCLOAK_REALM:fc3-codeflix}
  host: ${KEYCLOAK_HOST:http://localhost:8443}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: railway
  url: ${DATABASE_MYSQL_URL:localhost:3306}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none