spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
      - org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration

keycloak:
  enabled: false

mysql:
  username: root
  password: U3MMbFVFlQQRkhILS6HV
  schema: railway
  url: containers.railway.app:6849

server:
  port: ${PORT}
  undertow:
    threads:
      worker: 10
      io: 2