apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloack
spec:
  selector:
    matchLabels:
      app: keycloack
  template:
    metadata:
      labels:
        app: keycloack
    spec:
      containers:
      - name: keycloack
        image: quay.io/keycloak/keycloak:20.0.3
        ports:
        - containerPort: 8080
        command: [start-dev]
        env:
          - name: KEYCLOAK_ADMIN
            value: admin
          - name: KEYCLOAK_ADMIN_PASSWORD
            value: admin