amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456
  vhost: /

keycloak:
  realm: caixinha-auth-server
  host: https://lemur-5.cloud-iam.com/auth

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:3306

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2